
    export type StatusObject = {
      name: string;
      status: string;
      timestamp: string;
      onlinefor: string | null;
      offlineSince: string | null;
      lastSeen: string | null;
      timesOnline: number;
      firstSeen: Date | null;
      ts :any;
      lastSessionDuration: string | null;
    }

    export const statuses: StatusObject[] = [
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:1:57",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "9:1:57",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:8",
    "onlinefor": null,
    "offlineSince": "6 seconds",
    "lastSeen": "9:2:8",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:14",
    "onlinefor": null,
    "offlineSince": "12 seconds",
    "lastSeen": "9:2:14",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:21",
    "onlinefor": null,
    "offlineSince": "18 seconds",
    "lastSeen": "9:2:21",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:28",
    "onlinefor": null,
    "offlineSince": "24 seconds",
    "lastSeen": "9:2:28",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:34",
    "onlinefor": null,
    "offlineSince": "30 seconds",
    "lastSeen": "9:2:34",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:41",
    "onlinefor": null,
    "offlineSince": "36 seconds",
    "lastSeen": "9:2:41",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:47",
    "onlinefor": null,
    "offlineSince": "42 seconds",
    "lastSeen": "9:2:47",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:2:54",
    "onlinefor": null,
    "offlineSince": "48 seconds",
    "lastSeen": "9:2:54",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:0",
    "onlinefor": null,
    "offlineSince": "54 seconds",
    "lastSeen": "9:3:0",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:7",
    "onlinefor": null,
    "offlineSince": "60 seconds",
    "lastSeen": "9:3:7",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:13",
    "onlinefor": null,
    "offlineSince": "66 seconds",
    "lastSeen": "9:3:13",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:20",
    "onlinefor": null,
    "offlineSince": "72 seconds",
    "lastSeen": "9:3:20",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:26",
    "onlinefor": null,
    "offlineSince": "78 seconds",
    "lastSeen": "9:3:26",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:33",
    "onlinefor": null,
    "offlineSince": "84 seconds",
    "lastSeen": "9:3:33",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:39",
    "onlinefor": null,
    "offlineSince": "90 seconds",
    "lastSeen": "9:3:39",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:46",
    "onlinefor": null,
    "offlineSince": "96 seconds",
    "lastSeen": "9:3:46",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:53",
    "onlinefor": null,
    "offlineSince": "102 seconds",
    "lastSeen": "9:3:53",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:3:59",
    "onlinefor": null,
    "offlineSince": "108 seconds",
    "lastSeen": "9:3:59",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:6",
    "onlinefor": null,
    "offlineSince": "114 seconds",
    "lastSeen": "9:4:6",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:12",
    "onlinefor": null,
    "offlineSince": "120 seconds",
    "lastSeen": "9:4:12",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:19",
    "onlinefor": null,
    "offlineSince": "126 seconds",
    "lastSeen": "9:4:19",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:25",
    "onlinefor": null,
    "offlineSince": "132 seconds",
    "lastSeen": "9:4:25",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:32",
    "onlinefor": null,
    "offlineSince": "138 seconds",
    "lastSeen": "9:4:32",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:38",
    "onlinefor": null,
    "offlineSince": "144 seconds",
    "lastSeen": "9:4:38",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:45",
    "onlinefor": null,
    "offlineSince": "150 seconds",
    "lastSeen": "9:4:45",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:51",
    "onlinefor": null,
    "offlineSince": "156 seconds",
    "lastSeen": "9:4:51",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:4:58",
    "onlinefor": null,
    "offlineSince": "162 seconds",
    "lastSeen": "9:4:58",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:4",
    "onlinefor": null,
    "offlineSince": "168 seconds",
    "lastSeen": "9:5:4",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:11",
    "onlinefor": null,
    "offlineSince": "174 seconds",
    "lastSeen": "9:5:11",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:18",
    "onlinefor": null,
    "offlineSince": "180 seconds",
    "lastSeen": "9:5:18",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:24",
    "onlinefor": null,
    "offlineSince": "186 seconds",
    "lastSeen": "9:5:24",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:31",
    "onlinefor": null,
    "offlineSince": "192 seconds",
    "lastSeen": "9:5:31",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:37",
    "onlinefor": null,
    "offlineSince": "198 seconds",
    "lastSeen": "9:5:37",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:44",
    "onlinefor": null,
    "offlineSince": "204 seconds",
    "lastSeen": "9:5:44",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:50",
    "onlinefor": null,
    "offlineSince": "210 seconds",
    "lastSeen": "9:5:50",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:5:57",
    "onlinefor": null,
    "offlineSince": "216 seconds",
    "lastSeen": "9:5:57",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:3",
    "onlinefor": null,
    "offlineSince": "222 seconds",
    "lastSeen": "9:6:3",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:10",
    "onlinefor": null,
    "offlineSince": "228 seconds",
    "lastSeen": "9:6:10",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:16",
    "onlinefor": null,
    "offlineSince": "234 seconds",
    "lastSeen": "9:6:16",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:23",
    "onlinefor": null,
    "offlineSince": "240 seconds",
    "lastSeen": "9:6:23",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:30",
    "onlinefor": null,
    "offlineSince": "246 seconds",
    "lastSeen": "9:6:30",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:36",
    "onlinefor": null,
    "offlineSince": "252 seconds",
    "lastSeen": "9:6:36",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:43",
    "onlinefor": null,
    "offlineSince": "258 seconds",
    "lastSeen": "9:6:43",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:49",
    "onlinefor": null,
    "offlineSince": "264 seconds",
    "lastSeen": "9:6:49",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:6:56",
    "onlinefor": null,
    "offlineSince": "270 seconds",
    "lastSeen": "9:6:56",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:2",
    "onlinefor": null,
    "offlineSince": "276 seconds",
    "lastSeen": "9:7:2",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:9",
    "onlinefor": null,
    "offlineSince": "282 seconds",
    "lastSeen": "9:7:9",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:15",
    "onlinefor": null,
    "offlineSince": "288 seconds",
    "lastSeen": "9:7:15",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:22",
    "onlinefor": null,
    "offlineSince": "294 seconds",
    "lastSeen": "9:7:22",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:28",
    "onlinefor": null,
    "offlineSince": "300 seconds",
    "lastSeen": "9:7:28",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:35",
    "onlinefor": null,
    "offlineSince": "306 seconds",
    "lastSeen": "9:7:35",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:42",
    "onlinefor": null,
    "offlineSince": "312 seconds",
    "lastSeen": "9:7:42",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:48",
    "onlinefor": null,
    "offlineSince": "318 seconds",
    "lastSeen": "9:7:48",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:7:55",
    "onlinefor": null,
    "offlineSince": "324 seconds",
    "lastSeen": "9:7:55",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:1",
    "onlinefor": null,
    "offlineSince": "330 seconds",
    "lastSeen": "9:8:1",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:8",
    "onlinefor": null,
    "offlineSince": "336 seconds",
    "lastSeen": "9:8:8",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:15",
    "onlinefor": null,
    "offlineSince": "342 seconds",
    "lastSeen": "9:8:15",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:21",
    "onlinefor": null,
    "offlineSince": "348 seconds",
    "lastSeen": "9:8:21",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:28",
    "onlinefor": null,
    "offlineSince": "354 seconds",
    "lastSeen": "9:8:28",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:35",
    "onlinefor": null,
    "offlineSince": "360 seconds",
    "lastSeen": "9:8:35",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:41",
    "onlinefor": null,
    "offlineSince": "366 seconds",
    "lastSeen": "9:8:41",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:48",
    "onlinefor": null,
    "offlineSince": "372 seconds",
    "lastSeen": "9:8:48",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:8:55",
    "onlinefor": null,
    "offlineSince": "378 seconds",
    "lastSeen": "9:8:55",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:1",
    "onlinefor": null,
    "offlineSince": "384 seconds",
    "lastSeen": "9:9:1",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:8",
    "onlinefor": null,
    "offlineSince": "390 seconds",
    "lastSeen": "9:9:8",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:14",
    "onlinefor": null,
    "offlineSince": "396 seconds",
    "lastSeen": "9:9:14",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:21",
    "onlinefor": null,
    "offlineSince": "402 seconds",
    "lastSeen": "9:9:21",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:27",
    "onlinefor": null,
    "offlineSince": "408 seconds",
    "lastSeen": "9:9:27",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:34",
    "onlinefor": null,
    "offlineSince": "414 seconds",
    "lastSeen": "9:9:34",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:41",
    "onlinefor": null,
    "offlineSince": "420 seconds",
    "lastSeen": "9:9:41",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:47",
    "onlinefor": null,
    "offlineSince": "426 seconds",
    "lastSeen": "9:9:47",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:9:54",
    "onlinefor": null,
    "offlineSince": "432 seconds",
    "lastSeen": "9:9:54",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:0",
    "onlinefor": null,
    "offlineSince": "438 seconds",
    "lastSeen": "9:10:0",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:7",
    "onlinefor": null,
    "offlineSince": "444 seconds",
    "lastSeen": "9:10:7",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:13",
    "onlinefor": null,
    "offlineSince": "450 seconds",
    "lastSeen": "9:10:13",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:20",
    "onlinefor": null,
    "offlineSince": "456 seconds",
    "lastSeen": "9:10:20",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:27",
    "onlinefor": null,
    "offlineSince": "462 seconds",
    "lastSeen": "9:10:27",
    "timesOnline": 0,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:10:33",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "9:10:33",
    "timesOnline": 1,
    "firstSeen": null,
    "ts": "9:1:55",
    "lastSessionDuration": "0 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:40",
    "onlinefor": null,
    "offlineSince": "13 seconds",
    "lastSeen": "9:10:40",
    "timesOnline": 1,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "13 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:46",
    "onlinefor": null,
    "offlineSince": "19 seconds",
    "lastSeen": "9:10:46",
    "timesOnline": 1,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "13 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:53",
    "onlinefor": null,
    "offlineSince": "25 seconds",
    "lastSeen": "9:10:53",
    "timesOnline": 1,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "13 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:10:59",
    "onlinefor": null,
    "offlineSince": "31 seconds",
    "lastSeen": "9:10:59",
    "timesOnline": 1,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "13 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:6",
    "onlinefor": "32 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:6",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:13",
    "onlinefor": "38 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:13",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:19",
    "onlinefor": "44 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:19",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:26",
    "onlinefor": "50 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:26",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:32",
    "onlinefor": "56 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:32",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:39",
    "onlinefor": "62 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:39",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:45",
    "onlinefor": "68 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:45",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:52",
    "onlinefor": "74 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:52",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:11:59",
    "onlinefor": "80 seconds",
    "offlineSince": null,
    "lastSeen": "9:11:59",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:12:5",
    "onlinefor": "86 seconds",
    "offlineSince": null,
    "lastSeen": "9:12:5",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:12:12",
    "onlinefor": "92 seconds",
    "offlineSince": null,
    "lastSeen": "9:12:12",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:12:19",
    "onlinefor": "98 seconds",
    "offlineSince": null,
    "lastSeen": "9:12:19",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:12:25",
    "onlinefor": "104 seconds",
    "offlineSince": null,
    "lastSeen": "9:12:25",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Online",
    "timestamp": "9:12:32",
    "onlinefor": "110 seconds",
    "offlineSince": null,
    "lastSeen": "9:12:32",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "32 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:12:38",
    "onlinefor": null,
    "offlineSince": "98 seconds",
    "lastSeen": "9:12:38",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:12:45",
    "onlinefor": null,
    "offlineSince": "104 seconds",
    "lastSeen": "9:12:45",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:12:51",
    "onlinefor": null,
    "offlineSince": "110 seconds",
    "lastSeen": "9:12:51",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:12:58",
    "onlinefor": null,
    "offlineSince": "116 seconds",
    "lastSeen": "9:12:58",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:5",
    "onlinefor": null,
    "offlineSince": "122 seconds",
    "lastSeen": "9:13:5",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:11",
    "onlinefor": null,
    "offlineSince": "128 seconds",
    "lastSeen": "9:13:11",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:18",
    "onlinefor": null,
    "offlineSince": "134 seconds",
    "lastSeen": "9:13:18",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:24",
    "onlinefor": null,
    "offlineSince": "140 seconds",
    "lastSeen": "9:13:24",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:31",
    "onlinefor": null,
    "offlineSince": "146 seconds",
    "lastSeen": "9:13:31",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:37",
    "onlinefor": null,
    "offlineSince": "152 seconds",
    "lastSeen": "9:13:37",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:44",
    "onlinefor": null,
    "offlineSince": "158 seconds",
    "lastSeen": "9:13:44",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:51",
    "onlinefor": null,
    "offlineSince": "164 seconds",
    "lastSeen": "9:13:51",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:13:57",
    "onlinefor": null,
    "offlineSince": "170 seconds",
    "lastSeen": "9:13:57",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:4",
    "onlinefor": null,
    "offlineSince": "176 seconds",
    "lastSeen": "9:14:4",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:11",
    "onlinefor": null,
    "offlineSince": "182 seconds",
    "lastSeen": "9:14:11",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:17",
    "onlinefor": null,
    "offlineSince": "188 seconds",
    "lastSeen": "9:14:17",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:24",
    "onlinefor": null,
    "offlineSince": "194 seconds",
    "lastSeen": "9:14:24",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:31",
    "onlinefor": null,
    "offlineSince": "200 seconds",
    "lastSeen": "9:14:31",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:37",
    "onlinefor": null,
    "offlineSince": "206 seconds",
    "lastSeen": "9:14:37",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:44",
    "onlinefor": null,
    "offlineSince": "212 seconds",
    "lastSeen": "9:14:44",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:50",
    "onlinefor": null,
    "offlineSince": "218 seconds",
    "lastSeen": "9:14:50",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:14:57",
    "onlinefor": null,
    "offlineSince": "224 seconds",
    "lastSeen": "9:14:57",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:4",
    "onlinefor": null,
    "offlineSince": "230 seconds",
    "lastSeen": "9:15:4",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:10",
    "onlinefor": null,
    "offlineSince": "236 seconds",
    "lastSeen": "9:15:10",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:17",
    "onlinefor": null,
    "offlineSince": "242 seconds",
    "lastSeen": "9:15:17",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:24",
    "onlinefor": null,
    "offlineSince": "248 seconds",
    "lastSeen": "9:15:24",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:31",
    "onlinefor": null,
    "offlineSince": "254 seconds",
    "lastSeen": "9:15:31",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:37",
    "onlinefor": null,
    "offlineSince": "260 seconds",
    "lastSeen": "9:15:37",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:44",
    "onlinefor": null,
    "offlineSince": "266 seconds",
    "lastSeen": "9:15:44",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:51",
    "onlinefor": null,
    "offlineSince": "272 seconds",
    "lastSeen": "9:15:51",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:15:58",
    "onlinefor": null,
    "offlineSince": "278 seconds",
    "lastSeen": "9:15:58",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:4",
    "onlinefor": null,
    "offlineSince": "284 seconds",
    "lastSeen": "9:16:4",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:11",
    "onlinefor": null,
    "offlineSince": "290 seconds",
    "lastSeen": "9:16:11",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:17",
    "onlinefor": null,
    "offlineSince": "296 seconds",
    "lastSeen": "9:16:17",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:24",
    "onlinefor": null,
    "offlineSince": "302 seconds",
    "lastSeen": "9:16:24",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:30",
    "onlinefor": null,
    "offlineSince": "308 seconds",
    "lastSeen": "9:16:30",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:37",
    "onlinefor": null,
    "offlineSince": "314 seconds",
    "lastSeen": "9:16:37",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:44",
    "onlinefor": null,
    "offlineSince": "320 seconds",
    "lastSeen": "9:16:44",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:50",
    "onlinefor": null,
    "offlineSince": "326 seconds",
    "lastSeen": "9:16:50",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:16:57",
    "onlinefor": null,
    "offlineSince": "332 seconds",
    "lastSeen": "9:16:57",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:17:4",
    "onlinefor": null,
    "offlineSince": "338 seconds",
    "lastSeen": "9:17:4",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:17:10",
    "onlinefor": null,
    "offlineSince": "344 seconds",
    "lastSeen": "9:17:10",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "9:17:17",
    "onlinefor": null,
    "offlineSince": "350 seconds",
    "lastSeen": "9:17:17",
    "timesOnline": 2,
    "firstSeen": "9:10:33",
    "ts": "9:1:55",
    "lastSessionDuration": "98 seconds"
  }
];
  